version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports: 
      - "8080:8080"
    tty: true # コンテナの起動永続化
  db:
    image: postgres:10.13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge
    ports:
      - 5432:5432
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
