version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/y3kawaguchi/knowledge
    steps:
      - checkout
      - run: make build_linux
      - run: make test
